# Generated by Django 4.2.16 on 2024-11-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(help_text='Longitud geográfica del inmueble')),
                ('latitude', models.FloatField(help_text='Latitud geográfica del inmueble')),
                ('housing_median_age', models.FloatField(help_text='Edad promedio de las viviendas en el área')),
                ('total_rooms', models.IntegerField(help_text='Número total de habitaciones en el inmueble')),
                ('total_bedrooms', models.IntegerField(help_text='Número total de dormitorios en el inmueble')),
                ('population', models.IntegerField(help_text='Población en el área')),
                ('households', models.IntegerField(help_text='Número de hogares en el área')),
                ('median_income', models.FloatField(help_text='Ingreso medio en el área (en decenas de miles)')),
                ('median_house_value', models.FloatField(help_text='Valor medio del inmueble')),
                ('ocean_proximity', models.CharField(choices=[('NEAR OCEAN', 'Cerca del océano'), ('INLAND', 'Interior'), ('NEAR BAY', 'Cerca de la bahía'), ('ISLAND', 'Isla'), ('<1H OCEAN', 'A menos de 1 hora del océano')], help_text='Proximidad al océano', max_length=50)),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'houses',
                'ordering': ['population', 'median_house_value'],
            },
        ),
    ]
