# Generated by Django 4.2.16 on 2024-11-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='households',
            field=models.FloatField(help_text='Número de hogares en el área'),
        ),
        migrations.AlterField(
            model_name='house',
            name='population',
            field=models.FloatField(help_text='Población en el área'),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_bedrooms',
            field=models.FloatField(help_text='Número total de dormitorios en el inmueble'),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_rooms',
            field=models.FloatField(help_text='Número total de habitaciones en el inmueble'),
        ),
    ]
